filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

i5k/urls.py
from datetime import datetime
from django.conf.urls import patterns, include, url
from app.forms import BootstrapAuthenticationForm, BootStrapPasswordChangeForm, BootStrapPasswordResetForm, BootStrapSetPasswordForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.sites.models import Site
admin.autodiscover()
#admin.site.unregister(Site)

#from filebrowser.sites import site

urlpatterns = patterns('',
    # Examples:
    url(r'^home$', 'dashboard.views.dashboard', name='dashboard'),
    #url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name='doc'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^proxy/', include('proxy.urls', namespace='proxy')),
    url(r'^webapollo/', include('webapollo.urls', namespace='webapollo')),

    # user authentication
    url(r'^set_institution$', 'app.views.set_institution', name='set_institution'),
    url(r'^info_change$', 'app.views.info_change', name='info_change'),
    url(r'^register$', 'app.views.register', name='register'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            },
        },
        name='login'),
    url(r'^logout$', 'app.views.logout_all', name='logout'),
    url(r'^password_reset$', 
        'django.contrib.auth.views.password_reset',
        {
            'template_name': 'app/password_reset.html',
            'password_reset_form': BootStrapPasswordResetForm,
            'extra_context':
            {
                'title': 'Password reset',
                'year': datetime.now().year,
            },
        },
        name='password_reset'),
    url(r'^password_reset_done$',
        'django.contrib.auth.views.password_reset_done',
        {
            'template_name': 'app/password_reset_done.html',
            'extra_context':
            {
                'title': 'Password reset sent',
                'year': datetime.now().year,
            },
        },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {
            'template_name': 'app/password_reset_confirm.html',
            'set_password_form': BootStrapSetPasswordForm,
            'extra_context':
            {
                'year': datetime.now().year,
            },
        },
        name='password_reset_confirm'),
    url(r'^reset_complete$',
        'django.contrib.auth.views.password_reset_complete',
        {
            'template_name': 'app/password_reset_complete.html',
            'extra_context':
            {
                'title': 'Password reset complete',
                'year': datetime.now().year,
            },
        },
        name='password_reset_complete'),
    url(r'^password_change_done$',
        'django.contrib.auth.views.password_change_done',
        {
            'template_name': 'app/password_change_done.html',
            'extra_context':
            {
                'title': 'Password changed',
                'year': datetime.now().year,
            },
        },
        name='password_change_done'),
    url(r'^password_change$',
        #'django.contrib.auth.views.password_change',
        'app.views.password_change',
        {
            'template_name': 'app/password_change.html',
            'password_change_form': BootStrapPasswordChangeForm,
            'post_change_redirect': 'password_change_done',
            'extra_context':
            {
                'title': 'Change password',
                'year': datetime.now().year,
            },
        },
        name='password_change'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # BLAST
    url(r'^blast/', include('blast.urls', namespace='blast')),
    # BLAST
    url(r'^data/', include('data.urls', namespace='data')),
)
from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

webapollo/urls.py
from django.conf.urls import *
from . import views


urlpatterns = patterns('',
    #url(r'^$', views.index, name='index'),
    url(r'^panel$', views.panel, name='panel'),
    url(r'^admin/manage$', views.manage, name="manage"),
    url(r'^admin/bulk-remind$', views.bulk_remind, name="bulk-remind"),
    url(r'^admin/user/(?P<user_id>[0-9]+)$', views.user_permission, name="user_permission"),
    url(r'^admin/species/(?P<species_name>[a-z]{6})$', views.species_user, name="species_user"),
    url(r'^apply$', views.apply, name='apply'),
    url(r'^reject$', views.reject, name='reject'),
    url(r'^bulk-reject$', views.bulk_reject, name='bulk-reject'),
    url(r'^history$', views.history, name='history'),
    url(r'^approve$', views.approve, name='approve'),
    url(r'^bulk-approve$', views.bulk_approve, name='bulk-approve'),
    url(r'^remind$', views.remind, name='remind'),
    url(r'^adduser$', views.adduser, name='adduesr'),
    url(r'^remove$', views.remove, name='remove'),
    url(r'^eligible$', views.eligible, name='eligible'),
    url(r'^(?P<species_name>[a-z]{6})$', views.species, name="species"),
)

webapollo/views.py
# coding: utf-8
import requests, json, sys
from datetime import datetime
from pytz import timezone
from django.db import connection
from django.db.models import Q
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User, Permission
from django.http import HttpResponse, HttpResponseRedirect
from django.core.cache import cache
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.utils import html
from django.template import Context
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage
from .models import Species, SpeciesPassword, Registration, insert_species_permission, delete_species_permission
from app.models import Profile
from app.views import checkOAuth, ajax_login_required


@login_required
def get_species(request):
    content_type = ContentType.objects.get_for_model(Species)
    perms = request.user.user_permissions.filter(content_type=content_type)
    owner_set = set()
    access_set = set()
    for perm in perms:
        # example of perm.name: 'cercap_write', 'anogla_owner'
        s = perm.name.split('_', 2)[0]
        p = perm.name.split('_', 2)[1]
        if p == 'owner':
            owner_set.add(s)
        else:
            access_set.add(s)
    access_set = access_set.difference(owner_set)
    
    # generate the list of authorized species
    species_list = []
    for sname in owner_set:
        species = Species.objects.get(name=sname)
        applicants = User.objects.filter(registration__species=species, registration__status='Pending').distinct()
        apply_records = []
        for applicant in applicants:
            apply_records.append(Registration.objects.select_related('user').filter(species=species, user=applicant).latest('submission_time'))
        species_owners = User.objects.filter(user_permissions__codename=sname+'_owner').distinct().order_by('last_name')
        species_users = User.objects.filter(~Q(user_permissions__codename=sname+'_owner'),Q(user_permissions__codename__startswith=sname)).distinct().order_by('last_name')
        species_list.append({'name': sname, 'full_name': species.full_name, 'is_owner': True, 'owners': species_owners, 'users': species_users, 'apply_records': apply_records,})
    species_list.sort(key=lambda k:k['name'])
    access_list = []
    for sname in access_set:
        species = Species.objects.get(name=sname)
        species_owners = User.objects.filter(user_permissions__codename=sname+'_owner').distinct().order_by('last_name')
        species_users = User.objects.filter(~Q(user_permissions__codename=sname+'_owner'),Q(user_permissions__codename__startswith=sname)).distinct().order_by('last_name')
        access_list.append({'name': sname, 'full_name': species.full_name, 'is_owner': False, 'owners': species_owners, 'users': species_users, })
    access_list.sort(key=lambda k:k['name'])
    species_list.extend(access_list)
    
    # generate the list of unauthorized species
    unauth_set = set()
    all_species = Species.objects.all()
    for s in all_species: 
        unauth_set.add(s.name)
    unauth_set = unauth_set.difference(owner_set)
    unauth_set = unauth_set.difference(access_set)
    unauth_list = []
    interested_list = []
    for sname in unauth_set:     
        # check applying record first
        species = Species.objects.get(name=sname)
        apply_records = Registration.objects.filter(user=request.user, species=species).order_by('-submission_time')
        if not apply_records:
            unauth_list.append({'name': sname, 'full_name': species.full_name, 'status':'New',})
        elif apply_records[0].status == 'Pending':
            interested_list.append({'name': sname, 'full_name': species.full_name, 'status':'Pending', 'apply_records': apply_records,})
        elif apply_records[0].status == 'Rejected':
            interested_list.append({'name': sname, 'full_name': species.full_name, 'status':'Rejected', 'apply_records': apply_records,})
        elif apply_records[0].status == 'Removed':
            interested_list.append({'name': sname, 'full_name': species.full_name, 'status':'Removed', 'apply_records': apply_records,})
        else: # status is 'Approved' or 'Added'
            raise Exception('Severe permission errors!')
    unauth_list.sort(key=lambda k:k['name'])
    interested_list.sort(key=lambda k:k['name'])

    return species_list, interested_list, unauth_list


@login_required
def index(request):
    species_list, interested_species_list, unauth_species_list = get_species(request)
    return render(
        request,
        'webapollo/webapollo.html', {
        'year': datetime.now().year,
        'title': 'Web Apollo',
        'species_list': species_list,
        'interested_species_list': interested_species_list,
        'unauth_species_list': unauth_species_list,
        'isOAuth': checkOAuth(request.user),
    })

@login_required
def panel(request):
    species_list, interested_species_list, unauth_species_list = get_species(request)
    return render(
        request,
        'webapollo/panel.html', {
        'year': datetime.now().year,
        'title': 'Web Apollo Application',
        'species_list': species_list,
        'interested_species_list': interested_species_list,
        'unauth_species_list': unauth_species_list,
    })

@ajax_login_required
def apply(request):
    if request.is_ajax():
        if request.method == 'POST':
            comment = html.escape(request.POST['comment'])
            comment = comment[:200] if len(comment) > 200 else comment
            try:
                _species = Species.objects.get(name=request.POST['species_name'])
                _registration = Registration(user=request.user, species=_species, submission_comment=comment)
                _registration.save()

                # email to the applicant and contacts
                subject = 'Web Apollo registration for ' + _species.full_name
                to = [request.user.email]
                ctx = {
                    'full_name': request.user.get_full_name(),
                    'species': _species.full_name,
                }
                message = render_to_string('webapollo/email/register.txt', ctx)
                EmailMessage(subject, message, to=to).send()
                subject = 'New annotator for ' + _species.full_name
                owners = User.objects.filter(user_permissions__codename=_species.name+'_owner')
                for owner in owners:
                    to =[owner.email]
                    ctx = {
                        'first_name': owner.first_name,
                        'user_full_name': request.user.get_full_name(),
                        'species': _species.full_name,
                        'website': settings.HOSTNAME + settings.LOGIN_REDIRECT_URL,
                    }
                    message = render_to_string('webapollo/email/new_annotator_request.txt', ctx)
                    EmailMessage(subject, message, to=to).send()
                
                return HttpResponse(json.dumps({'succeeded': True, 'submission_time': _registration.submission_time.astimezone(timezone('US/Eastern')).strftime('%b. %d, %Y, %I:%M %p'), 'comment': comment,}), content_type='application/json')
            except: #ObjectDoesNotExist:
                print 'Exception in webapollo_apply: ', sys.exc_info()[0]
                return HttpResponse(json.dumps({'succeeded': False}), content_type='application/json')
    return HttpResponse(json.dumps({ 'succeeded': False }), content_type='application/json')


def do_reject(sname, uname, comment, owner):
    try:
        _species = Species.objects.get(name=sname)
        _user = User.objects.get(username=uname)
        _registration = Registration.objects.get(user=_user, species=_species, status='Pending')
        _registration.decision_comment = 'Reject by ' + owner
        if comment:
            _registration.decision_comment = 'from ' + request.user.username + ': '+ comment
        _registration.decision_time = datetime.now()
        _registration.status = 'Rejected'
        _registration.save()

        # email to the applicant and contacts
        subject = 'Your application for annotating ' + _species.full_name + ' in Web Apollo'
        to = [_user.email]
        ctx = {
            'full_name': _user.get_full_name(),
            'species': _species.full_name,
            'website': settings.HOSTNAME + reverse('webapollo:panel'),
        }
        message = render_to_string('webapollo/email/rejection.txt', ctx)
        EmailMessage(subject, message, to=to).send()
        return True
    except:
        return False    

@ajax_login_required
def reject(request):
    if request.is_ajax():
        if request.method == 'POST':         
            comment = html.escape(request.POST['comment'])
            if comment:
                comment = comment[:200] if len(comment) > 200 else comment
            is_done = do_reject(request.POST['species_name'], request.POST['username'], comment, request.user.username)
            if is_done:
                return HttpResponse(json.dumps({'succeeded': True}), content_type='application/json')
            else: #ObjectDoesNotExist:
                print 'Exception in webapollo_reject ', sys.exc_info()[0]
                return HttpResponse(json.dumps({'succeeded': False}), content_type='application/json')
                
    return HttpResponse(json.dumps({ 'succeeded': False }), content_type='application/json')

@ajax_login_required
def bulk_reject(request):
    if request.is_ajax():
        if request.method == 'POST':
            num = request.POST.get('num')
            for i in xrange(int(num)):

webapollo/templates/webapollo/manage.html
{% extends "admin/base_site.html" %}
{% load admin_static %}{% load suit_tags %}{% load i18n %}


{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/tabletools/2.2.3/css/dataTables.tableTools.css">
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumb">
    <li><a href="{% url 'admin:index' %}">Home</a><span class="divider">&raquo;</span></li>
    <li>Webapollo<span class="divider">&raquo;</span></li>
    <li class="active">Management</li>
  </ul>
{% endblock %}


{% block content %}
{{ block.super }}
<div id="pendings">
  {% if pendings %}
  <div id="alert"></div>
  <p style="padding-bottom:1em;">
    <span id='remind-count' style='font-size: large;'>0</span> users selected &nbsp;&nbsp;
    <button type="button" class="btn btn-primary" id="btn-admin-remind">Remind Coordinators</button>
    <input type="hidden" id="hidden-admin-remind" value="">
  </p>
  <table id="table-pendings" class="table display compact">
  <caption><h2>Pending Requests</h2></caption>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Species</th>
      <th>Submission time</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    {% for pending in pendings %}
      <tr id="tr-{{pending.user.username}}-{{pending.species.name}}">
        <td>{{pending.user.first_name}} {{pending.user.last_name}}</td>
        <td>{{pending.species.name}}</td>
        <td>{{pending.submission_time | date:"M d Y" }}</td>
        <td>{{pending.submission_comment}}</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
  <hr>
  {% endif %}
</div>
<!-- Users -->
<div id="users">
  <table id="table-users" class="table display compact">
  <caption><h2>Users</h2></caption>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Username</th>
      <th>Institution</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <td><a href="./user/{{user.id}}">{{user.full_name}}</a></td>
        <td>{{user.username}}</td>
        <td>{{user.institution}}</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
<hr>
<!-- Species -->
<div id="species">
  <table id="table-species" class="table display compact">
  <caption><h2>Species</h2></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Coordinators</th>
      <th>Annotators</th>
    </tr>
  </thead>
  <tbody>
    {% for s in species %}
      <tr>
        <td><a href="./species/{{s.name}}">{{s.name}} ({{s.full_name}})</a></td>
        <td>{{s.owner}}</td>
        <td>{{s.annotator}}</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock %}


{% block extrajs %}
  {{ block.super }}
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/tabletools/2.2.3/js/dataTables.tableTools.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/f2c75b7247b/sorting/datetime-moment.js"></script>
  <script src="{% static 'webapollo/scripts/admin-manage.js' %}"></script>
{% endblock %}

webapollo/templates/webapollo/species_user.html
{% extends "admin/base_site.html" %}
{% load admin_static %}{% load suit_tags %}{% load i18n %}


{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/tabletools/2.2.3/css/dataTables.tableTools.css">
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumb">
    <li><a href="{% url 'admin:index' %}">Home</a><span class="divider">&raquo;</span></li>
    <li>Webapollo<span class="divider">&raquo;</span></li>
    <li><a href="{% url 'webapollo:manage' %}">Management</a><span class="divider">&raquo;</span></li>
    <li class="active">Species Users</li>

  </ul>
{% endblock %}


{% block content %}
{{ block.super }}
<div>
  <div class="alert alert-success" role="alert" id="alert-success" {%if not alert_success %}style="display:none;"{% endif %}>{{alert_text}}</div>
  <div class="alert alert-danger" role="alert" id="alert-danger" {%if not alert_fail %}style="display:none;"{% endif %}>{{alert_text}}</div>
  <h1>Users of {{species_name}}</h1>
  {% if users %}
  <form name="form-users" method="POST" action="" accept-charset="UTF-8">
  <p>
    <span id='users-count' style='font-size: large;'>0</span> users selected &nbsp;&nbsp;
    <button type="submit" class="btn btn-primary btn-users" id="btn-update" data-loading-text="Updating..." autocomplete="off">Update as coordinators</button>&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary btn-users" id="btn-remove" data-loading-text="Removing..." autocomplete="off">Remove users</button>&nbsp;&nbsp;
    <input type="hidden" name="usernames" id="input-users" value="123">
    <input type="hidden" name="operation" id="users-operation" value="abc">
  </p>
  </form>
  <table id="table-users" class="table display compact">
  <caption><h2>Annotators</h2></caption>  
  <thead>
    <tr>
      <th>Full name</th>
      <th>Username</th>
      <th>Institution</th>
      <th>coordinator</th>
    </tr>
  </thead>
  <tbody>
    {% for u in users %}
      <tr>
        <td>{{u.full_name}}</td>
        <td>{{u.username}}</td>
        <td>{{u.institution}}</td>
        <td>{% if u.is_owner %}<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>{% endif %}</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
  <hr>
  {% endif %}
  {% if candidates %}
  <form name="form-candidates" method="POST" action="" accept-charset="UTF-8">
  <p style="padding-top:1em;">
    <span id='candidates-count' style='font-size: large;'>0</span> users selected &nbsp;&nbsp;
    <button type="submit" class="btn btn-primary btn-candidates" id="btn-adduser" data-loading-text="Adding..." autocomplete="off">Add as annotators</button>&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary btn-candidates" id="btn-addowner" data-loading-text="Adding..." autocomplete="off">Add as coordinators</button>&nbsp;&nbsp;
    <input type="hidden" name="usernames" id="input-candidates" value="">
    <input type="hidden" name="operation" id="candidates-operation" value="">
  </p>
  </form>
  <table id="table-candidates" class="table display compact">
  <caption><h2>Candidates</h2></caption>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Username</th>
      <th>Institution</th>
    </tr>
  </thead>
  <tbody>
    {% for c in candidates %}
      <tr>
        <td>{{c.full_name}}</td>
        <td>{{c.username}}</td>
        <td>{{c.institution}}</td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
  
  {% endif %}
</div>
{% endblock %}


{% block extrajs %}
  {{ block.super }}
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/tabletools/2.2.3/js/dataTables.tableTools.min.js"></script>
  <script src="{% static 'webapollo/scripts/admin-species-user.js' %}"></script>
{% endblock %}

webapollo/templates/webapollo/user_permission.html
{% extends "admin/base_site.html" %}
{% load admin_static %}{% load suit_tags %}{% load i18n %}


{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/tabletools/2.2.3/css/dataTables.tableTools.css">
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css">
  <style>
    tr td:first-child, tr th:first-child { text-align: center; }
    tr td:first-child:before, tr th:first-child:before { 
        content: "\f096"; /* fa-square-o */
        font-family: FontAwesome;
    }
    tr.selected td:first-child:before, tr.selected th:first-child:before {
        content: "\f046"; /* fa-check-square-o */
    }
  </style>
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumb">
    <li><a href="{% url 'admin:index' %}">Home</a><span class="divider">&raquo;</span></li>
    <li>Webapollo<span class="divider">&raquo;</span></li>
    <li><a href="{% url 'webapollo:manage' %}">Management</a><span class="divider">&raquo;</span></li>
    <li class="active">User Permissions</li>

  </ul>
{% endblock %}


{% block content %}
{{ block.super }}
<div>
  <h1>Permissions of {{user.full_name}} ({{user.username}}), {{user.institution}}</h1>
  <p style="padding-bottom:1em;">
    <span id='count' style='font-size: large;'>0</span> species selected &nbsp;&nbsp;
    <button type="button" class="btn btn-primary" id="btn-update" data-loading-text="Updating..." autocomplete="off">Update permissions</button>&nbsp;&nbsp;
    <span id="alert" style="font-size: large; display:none;"></span>
  </p>
  <table id="table-user-permission" class="table display compact">
  <caption></caption>
  <thead>
    <tr>
      <th id="select-all"></th>
      <th>Species</th>
      <th>Read</th>
      <th>Write</th>
      <th>Publish</th>
      <th>Admin</th>
      <th>Owner</th>
    </tr>
  </thead>
  <tbody>
    {% for species in species_list %}
      <tr id="{{species.name}}">
        <td></td>
        <td>{{species.name}} ({{species.full_name}})</td>
        <td><input type="checkbox" name="read" value="1" {% if species.perm_values.read %} checked {% endif %} {% if species.perm_values.owner %} disabled {% endif %}></td>
        <td><input type="checkbox" name="write" value="2" {% if species.perm_values.write %} checked {% endif %} {% if species.perm_values.owner %} disabled {% endif %}></td>
        <td><input type="checkbox" name="publist" value="4" {% if species.perm_values.publish %} checked {% endif %} {% if species.perm_values.owner %} disabled {% endif %}></td>
        <td><input type="checkbox" name="admin" value="8" {% if species.perm_values.admin %} checked {% endif %} {% if species.perm_values.owner %} disabled {% endif %}></td>
        <td><input type="checkbox" name="owner" value="0" {% if species.perm_values.owner %} checked {% endif %}></td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock %}


{% block extrajs %}
  {{ block.super }}
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/tabletools/2.2.3/js/dataTables.tableTools.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
  <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/f2c75b7247b/sorting/datetime-moment.js"></script>
  <script src="{% static 'webapollo/scripts/admin-user-permission.js' %}"></script>
{% endblock %}