blast/urls.py
from django.conf.urls import patterns, url, include
from blast import views
from .api import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'organism', OrganismViewSet)
router.register(r'seqtype', SequenceTypeViewSet)
router.register(r'blastdb', BlastDbViewSet)
router.register(r'seq', SequenceViewSet)
router.register(r'task', BlastQueryRecordViewSet)
router.register(r'user', UserViewSet)

urlpatterns = patterns('',
    # ex: /blast/
    url(r'^$', views.create, name='create'),
    #url(r'^iframe$', views.create, {'iframe': True}, name='iframe'),
    # ex: /blast/5/
    url(r'^(?P<task_id>[0-9a-zA-Z]+)$', views.retrieve, name='retrieve'),
    url(r'^(?P<task_id>[0-9a-zA-Z]+)/status$', views.status, name='status'),
    #url(r'^read_gff3/(?P<task_id>[0-9a-fA-F]*)/*(?P<dbname>[\w\-\|.]*)/*$', views.read_gff3, name='read_gff3'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),
    url('^user-tasks/(?P<user_id>[0-9]+)$', views.user_tasks),
)

filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

i5k/urls.py
from datetime import datetime
from django.conf.urls import patterns, include, url
from app.forms import BootstrapAuthenticationForm, BootStrapPasswordChangeForm, BootStrapPasswordResetForm, BootStrapSetPasswordForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.sites.models import Site
admin.autodiscover()
#admin.site.unregister(Site)

#from filebrowser.sites import site

urlpatterns = patterns('',
    # Examples:
    url(r'^home$', 'dashboard.views.dashboard', name='dashboard'),
    #url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls'), name='doc'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^proxy/', include('proxy.urls', namespace='proxy')),
    url(r'^webapollo/', include('webapollo.urls', namespace='webapollo')),

    # user authentication
    url(r'^set_institution$', 'app.views.set_institution', name='set_institution'),
    url(r'^info_change$', 'app.views.info_change', name='info_change'),
    url(r'^register$', 'app.views.register', name='register'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            },
        },
        name='login'),
    url(r'^logout$', 'app.views.logout_all', name='logout'),
    url(r'^password_reset$', 
        'django.contrib.auth.views.password_reset',
        {
            'template_name': 'app/password_reset.html',
            'password_reset_form': BootStrapPasswordResetForm,
            'extra_context':
            {
                'title': 'Password reset',
                'year': datetime.now().year,
            },
        },
        name='password_reset'),
    url(r'^password_reset_done$',
        'django.contrib.auth.views.password_reset_done',
        {
            'template_name': 'app/password_reset_done.html',
            'extra_context':
            {
                'title': 'Password reset sent',
                'year': datetime.now().year,
            },
        },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {
            'template_name': 'app/password_reset_confirm.html',
            'set_password_form': BootStrapSetPasswordForm,
            'extra_context':
            {
                'year': datetime.now().year,
            },
        },
        name='password_reset_confirm'),
    url(r'^reset_complete$',
        'django.contrib.auth.views.password_reset_complete',
        {
            'template_name': 'app/password_reset_complete.html',
            'extra_context':
            {
                'title': 'Password reset complete',
                'year': datetime.now().year,
            },
        },
        name='password_reset_complete'),
    url(r'^password_change_done$',
        'django.contrib.auth.views.password_change_done',
        {
            'template_name': 'app/password_change_done.html',
            'extra_context':
            {
                'title': 'Password changed',
                'year': datetime.now().year,
            },
        },
        name='password_change_done'),
    url(r'^password_change$',
        #'django.contrib.auth.views.password_change',
        'app.views.password_change',
        {
            'template_name': 'app/password_change.html',
            'password_change_form': BootStrapPasswordChangeForm,
            'post_change_redirect': 'password_change_done',
            'extra_context':
            {
                'title': 'Change password',
                'year': datetime.now().year,
            },
        },
        name='password_change'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # BLAST
    url(r'^blast/', include('blast.urls', namespace='blast')),
    # BLAST
    url(r'^data/', include('data.urls', namespace='data')),
)
from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

webapollo/urls.py
from django.conf.urls import *
from . import views


urlpatterns = patterns('',
    #url(r'^$', views.index, name='index'),
    url(r'^panel$', views.panel, name='panel'),
    url(r'^admin/manage$', views.manage, name="manage"),
    url(r'^admin/bulk-remind$', views.bulk_remind, name="bulk-remind"),
    url(r'^admin/user/(?P<user_id>[0-9]+)$', views.user_permission, name="user_permission"),
    url(r'^admin/species/(?P<species_name>[a-z]{6})$', views.species_user, name="species_user"),
    url(r'^apply$', views.apply, name='apply'),
    url(r'^reject$', views.reject, name='reject'),
    url(r'^bulk-reject$', views.bulk_reject, name='bulk-reject'),
    url(r'^history$', views.history, name='history'),
    url(r'^approve$', views.approve, name='approve'),
    url(r'^bulk-approve$', views.bulk_approve, name='bulk-approve'),
    url(r'^remind$', views.remind, name='remind'),
    url(r'^adduser$', views.adduser, name='adduesr'),
    url(r'^remove$', views.remove, name='remove'),
    url(r'^eligible$', views.eligible, name='eligible'),
    url(r'^(?P<species_name>[a-z]{6})$', views.species, name="species"),
)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from datetime import datetime
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.apps import apps
from app.views import checkOAuth


@login_required
def dashboard(request):
    species_list = []
    if apps.is_installed('webapollo'):
        from webapollo.views import get_species
        from webapollo.models import Species, Registration
        from django.contrib.contenttypes.models import ContentType

        # species with permission to access
        content_type = ContentType.objects.get_for_model(Species)
        perms = request.user.user_permissions.filter(content_type=content_type)
        species_set = set()
        owner_set = set() # species with coordinator/owner permission
        for perm in perms:
            p = perm.name.split('_', 2)
            species_set.add(p[0])
            if p[1] == 'owner':
                owner_set.add(p[0])
        for sname in species_set:
            s = Species.objects.get(name=sname)
            species_list.append({
                'name': s.name,
                'full_name': s.full_name,
            })
        species_list.sort(key=lambda x: x['name'])

        # pending requests for the owner
        pendings = Registration.objects.filter(species__name__in=owner_set, status='Pending').order_by('species', 'submission_time')
        species_list, interested_species_list, unauth_species_list = get_species(request)

    return render(
        request,
        'dashboard/index.html', {
        'year': datetime.now().year,
        'title': 'Dashboard',
        'pendings': pendings,
        'species_list': species_list,
        'interested_species_list': interested_species_list,
        'unauth_species_list': unauth_species_list,
    })

dashboard/templates/dashboard/base.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block content %}

<!--<h2>{{ title }}</h2>-->

<ol class="breadcrumb" style="margin-top: 20px">
{% block dashboard-breadcrumb %}{% endblock %}
</ol>
<div class="row">
  <div class="col-md-3">
    <ul class="list-group">
      <li class="list-group-item">Apps</li>
      <li class="list-group-item"><a href='{% url "blast:create" %}'>BLAST</a></li>
      <li class="list-group-item"><a href='{% url "webapollo:index" %}'>Web Apollo</a></li>
    </ul>
    <ul class="list-group">
      <li class="list-group-item">Settings</li>
      {% if not isOAuth%} 
      <li class="list-group-item"><a href='{% url "password_change" %}'>Change Password</a></li>
      {% endif %}
      <li class="list-group-item"><a href='{% url "info_change" %}'>Update Account Info</a></li>
    </ul>
  </div>
  <div class="col-md-9">
    {% block dashboard-content %}{% endblock %}
  </div>
</div>

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block head-scripts %}
<style>
    .species-table {
        width: 100%;
        margin-bottom:0.5em;
    }
    .species-table td {
        vertical-align: middle; 
        width:50%;
    }
    .dataTables_empty {
        display: none;
    }
</style>
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/tabletools/2.2.3/css/dataTables.tableTools.css">
{% endblock %}

{% block content %}
<h2 style="padding-bottom:0.5em;">Blast&nbsp;&nbsp;<a href="{% url "blast:create" %}" role="button" class="btn btn-primary">Launch application</a></h2>
<table id="queries-{{user.id}}" class="display compact" cellspacing="0" width="100%">
    <caption>Blast queries</caption>
    <thead>
    <tr>
        <th>Submission time</th>
        <th>Status</th>
        <th>Link</th>
    </tr>
    </thead>
</table>
<hr>

<div class="anchor" id="pending_requests"></div>
<h2>Web Apollo</h2>
{% if pendings %}
<h3>Pending requests</h3>
<p>
    <span id="pendings-action">
    Click to select to
    <a href="#" id="link-approve">Approve</a>
    or
    <a href="#" id="link-reject">Reject</a>
    them. <span id='pendings-count' style='font-size: large;'>0</span> selected.
    </span>
    <span id="pendings-msg"></span>
</p>
<table id="pendings" class="display compact" cellspacing="0" width="100%">
    <caption>Pending requests</caption>
    <thead>
    <tr>
        <th>Organism</th>
        <th>Full name</th>
        <th>Institution</th>
        <th>Submitted</th>
        <th>Comment</th>
        <th>Username</th>
        <th>SpeciesShort</th>
    </tr>
    </thead>
    <tbody>
    {% for pending in pendings %}
        <tr id="tr-{{pending.user.username}}-{{pending.species.name}}">
          <td>{{pending.species.full_name}}</td>
          <td>{{pending.user.first_name}} {{pending.user.last_name}}</td>
          <td>{{pending.user.profile.institution}}</td>
          <td>{{pending.submission_time|date:"d M Y"}}</td>
          <td>{{pending.submission_comment}}</td>
          <td>{{pending.user.username}}</td>
          <td>{{pending.species.name}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<hr>
{% endif %}

<h3>Launch applications</h3>
{% if species_list %}
    {% for species in species_list%}
    <table class="species-table">
    <tr>
        <td>{{ species.full_name }}</td>
        <td>
            <a href="{% url 'webapollo:species' species.name %}" role="button" class="btn btn-primary" target="_blank">Launch</a>
            {% if species.is_owner%}
                <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapse-{{species.name}}" aria-expanded="false" aria-controls="collapse-{{species.name}}">Manage</button>
            {% else %}
                <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapse-{{species.name}}" aria-expanded="false" aria-controls="collapse-{{species.name}}">Info</button>
            {% endif %}
            </ul>
        </td>
    </tr>
    </table>    
    <div class="collapse" id="collapse-{{species.name}}">
        <div class="well">
        {% if species.is_owner%}
            <table class="table table-owner-annotators display compact" id="annotators-{{species.name}}">
            <caption>Annotators</caption>
            <thead>
              <tr>
                <th>Full Name</th>
                <th>Username</th>
                <th>Institution</th>
                <th><a href="#" data-toggle="modal" data-target="#addUserModal" data-whatever="{{species.name}}" >Add user</a></th>
              </tr>
            </thead>
            <tbody>
            {% for owner in species.owners %}
              <tr id="tr-{{owner.username}}-{{species.name}}">
                <td>
                  {{ owner.first_name }} {{ owner.last_name }} <span class="label label-default">Contact</span>
                </td>
                <td>{{ owner.username}}</td>
                <td>{{ owner.profile.institution}}</td>
                <td></td>
              </tr>
            {% endfor %}
            {% for user in species.users %}
              <tr id="tr-{{user.username}}-{{species.name}}">
                <td>{{user.first_name}} {{user.last_name}}</td>
                <td>{{user.username}}</td>
                <td>{{user.profile.institution}}</td>
                <td><a href="#" class="link-remove">Remove</a></td>
              </tr>
            {% endfor %}
            </tbody>
            </table>
        {% else %}
          {% if species.owners or species.users %}
            <table class="table table-annotators display compact">
            <caption>Annotators</caption>
            <thead>
              <tr>
                <th>Full Name</th>
                <th>Username</th>
                <th>Institution</th>
              </tr>
            </thead>
            <tbody>
            {% for owner in species.owners %}
              <tr>
                <td>
                    {{ owner.first_name }} {{ owner.last_name }} <span class="label label-default">Contact</span>
                </td>
                <td>{{ owner.username}}</td>
                <td>{{ owner.profile.institution}}</td>
              </tr>
            {% endfor %}
            {% for user in species.users %}
              <tr>
                <td>{{user.first_name}} {{user.last_name}}</td>
                <td>{{user.username}}</td>
                <td>{{user.profile.institution}}</td>
              </tr>
            {% endfor %}
            </tbody>
            </table>
          {% endif %}
        {% endif %}
        </div>
    </div>
    {% endfor %}
    <!-- addUserModal -->
    <div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog"><div class="modal-content">
    <div class="modal-body">
        <p id="addUserMsg">Click to select users to be annotators</p>
        <table class="table display compact table-adduser" id="adduser-table">
            <thead>
              <tr>
                <th>Full Name</th>
                <th>Username</th>
                <th>Institution</th>
              </tr>
            </thead>
            <tbody></tbody>
        </table>
        <p style="text-align:right; padding-top:1em;">
            <span style="float:left;"><span id='adduser-count' style='font-size: large;'>0</span> users selected</span>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>&nbsp;
            <button type="button" class="btn btn-primary" id="btn-addUserModal" data-loading-text="Adding...">Add selected users</button>
            <input type="hidden" id="hidden-addUserModal" value="">
        </p>
    </div>
    </div></div></div>
{% else %}
    <p>No organisms.</p>
{% endif %}
<hr>
<h3><a href='{% url "webapollo:panel" %}'>Apply for annotation</a></h3>

<!-- approveModal -->
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="approveModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-body">
    <p id="msg-approve"></p>
    <p style="text-align:right; padding-top:1em;">
    <button type="button" class="btn btn-default" data-dismiss="modal" id="btn-approve-close">Close</button>
</p>
</div>
</div></div></div>
{% endblock%}

{% block scripts %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/tabletools/2.2.3/js/dataTables.tableTools.min.js"></script>
<script src="{% static 'dashboard/scripts/dashboard.js' %}"></script>
{% endblock %}